apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
  labels:
    app:  redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name:  redis
        image:  redis
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        ports:
        - containerPort:  6379
          name:  api
        volumeMounts:
        - mountPath: "/data"
          name: redis-pv
      restartPolicy: Always
